export { Signup } from './Signup/Signup'
export { Home } from './Home/Home'
export { Movie } from './Movie/Movie'
export { Signin } from './Signin/Signin'
export { NotFound } from './NotFound/Notfound'
export { About } from './About/About'